name: Navi
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0
environment:
  sdk: ^3.7.2
dependencies:
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.3
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.9
  giffy_dialog: ^2.3.0
  http: ^1.3.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  jpush_flutter: ^3.2.0
  lottie: ^3.3.1
  shared_preferences: ^2.5.2
  stomp_dart_client: ^2.1.3
  web_socket_channel: ^3.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - lib/assets/icons/
    - lib/assets/images/
    - lib/assets/fonts/Inter-Regular.ttf
    - lib/assets/fonts/Inter-Bold.ttf
  fonts:
    - family: Inter
      fonts:
        - asset: lib/assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Inter-Bold.ttf
          weight: 700
