name: Navi
description: "A new Flutter project."
publish_to: "none"
version: 1.0.3
environment:
  # sdk: ^3.7.2
    sdk: ">=2.17.0 <3.0.0"
dependencies:
  app_settings: ^6.1.1
  cached_network_image: ^3.2.0
  connectivity_plus: ^5.0.0
  crypto: ^3.0.3
  dio: ^5.8.0+1
  encrypt: ^5.0.0
  fast_rsa: ^3.6.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.0
  flutter_screenutil: ^5.7.0
  flutter_svg: ^2.0.5
  giffy_dialog: ^1.8.0
  google_fonts: ^4.0.0
  http: ^0.13.5
  image_picker: 0.8.7+3
  intl: ^0.18.0
  jpush_flutter: ^3.2.0
  jverify: ^2.0.0
  lottie: ^2.3.0
  path_provider: ^2.1.0
  permission_handler: ^10.4.0
  photo_manager: 3.6.4
  photo_manager_image_provider: ^1.0.0
  provider: ^6.1.4
  shared_preferences: ^2.2.0
  stomp_dart_client: ^2.0.0
  web_socket_channel: ^2.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^5.0.0
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - lib/assets/icons/
    - lib/assets/images/
  fonts:
    - family: KumarOne
      fonts:
        - asset: lib/assets/fonts/KumarOne-Regular.ttf

    # Inter 字体家族（所有字重统一声明）
    - family: Inter
      fonts:
        - asset: lib/assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: lib/assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: lib/assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: lib/assets/fonts/Inter-Black.ttf
          weight: 900
        - asset: lib/assets/fonts/Inter-VariableFont_slnt,wght.ttf
          style: normal

    # Roboto 字体家族（基础声明）
    - family: Roboto
      fonts:
        - asset: lib/assets/fonts/Roboto-Regular.ttf
          weight: 400