name: flutterlearn2
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0
environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - lib/assets/icons/
    - lib/assets/images/
    - lib/assets/fonts/Inter-Regular.ttf
    - lib/assets/fonts/Inter-Bold.ttf
  fonts:
    - family: Inter
      fonts:
        - asset: lib/assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Inter-Bold.ttf
          weight: 700
